# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CWEt6Zysm-nyxqV999s4EeOkFMryib6Y
"""

def telefon_nomi(marka):
   if marka=="Samsung A15":
    return " Narxi :140$  Dyumi: 5 dpr"
   elif marka== "Samsung A25":
      return "200$"
   elif marka=="Samsung A35":
        return "220$"
   elif marka=="Samsung A55":
          return "280$"
   elif marka=="Samsung S24":
          return "700$"
   elif marka=="Samsung S24+":
            return "800$"
   elif marka=="Samsung S24 Ultra":
              return "1050$"
   elif marka=="iphone 11":
    return "250$"
   elif marka=="iphone 11pro":
      return "300$"
   elif marka=="iphone 11 pro max":
    return "350$"
   elif marka=="iphone 12":
      return "320$"


   else:
                return "Menejerga murojaat qiling"
marka=input("Telefon markasini kiriting")
natija=telefon_nomi(marka)
print(natija)